---
title: "EPSPS crops"
author: "Maxwel Coura Oliveira"
date: "8/22/2019"
output: pdf_document
---

```{r}
library(tidyverse)
library(patchwork)
```



```{r}
EPSPS <- read_csv("Crop_EPSPS.csv")
```


```{r}
EPSPS$Herbicide <- factor(EPSPS$Herbicide, levels = c("EPSPS-S", "EPSPS-RS", "EPSPS-R", "PPO-S", "PPO-RS", "PPO-R"), labels = c("EPSPS-Susceptible", "EPSPS-Segregating", "EPSPS-Resistant", "PPO-Susceptible", "PPO-Segregating", "PPO-Resistant"))
```



```{r}
EP <- EPSPS %>% 
  filter(Herb == "EPSPS")

p1<-ggplot(EP, aes(x=Herbicide, y=Perc, fill=Crop)) + geom_col(position = "stack",
     width = 0.5, color="black") + 
  facet_wrap(~Type, nrow = 1) + coord_flip() + theme_bw() +
  scale_fill_brewer(palette="Paired") + labs(x="", y="% of diversty in crops") + theme(legend.title = element_text(size=12, face = "bold"), strip.text = element_text(size=13, face="bold"),  panel.grid = element_blank(),
   axis.title = element_text(size=14, color="black"), axis.text = element_text(size=13, color="black"), legend.text = element_text(size=12), legend.position = "right") +
  ggsave("EPSPScrop.png", height = 8 , width=6, dpi=300) 
```

```{r}
PPO <- EPSPS %>% 
  filter(Herb == "PPO")

p2 <- ggplot(PPO, aes(x=Herbicide, y=Perc, fill=Crop)) + geom_col(position = "stack",
     width = 0.5, color="black") + 
  facet_wrap(~Type, nrow = 1) + coord_flip() + theme_bw() +
  scale_fill_brewer(palette="Paired") + labs(x="", y="% of diversty in crops") + theme(legend.title = element_text(size=12, face = "bold"), strip.text = element_text(size=13, face="bold"),  panel.grid = element_blank(),
   axis.title = element_text(size=14, color="black"), axis.text = element_text(size=13, color="black"), legend.text = element_text(size=12), legend.position = "right") +
  ggsave("PPOcrop.png", height = 8 , width=6, dpi=300) 
```


```{r}
(random | p1) + 
plot_annotation(tag_levels = c('A', 'B')) 
  
  
  
#  ggsave("Figure 5", height = 6, width = 12)
```


```{r}
library(gridExtra)
library(cowplot)
plot_grid(random, p1, nrow = 2, labels = c("A", "B"))+
  ggsave("Figure 5.png", height=12, width=6, dpi=600)
```

```{r}
((random | a ) / p1) + plot_annotation(tag_levels = c('A', 'B', 'C')) +
  ggsave("Figure 3.tiff", height = 10, width=12, dpi=300)
```

```{r}
((random2 | b ) / p2) + plot_annotation(tag_levels = c('A', 'B', 'C')) +
  ggsave("Figure 9.png", height = 10, width=12, dpi=600)
```


```{r}
library(gridExtra)
library(cowplot)
plot_grid(p1, p2, nrow = 1, labels = c("A", "B")) +
  ggsave("Figure 5.png", height=8, width=12, dpi=200)
```